import { FRONTEND_ROUTES, API_ROUTES as SHARED_API_ROUTES } from '../../../constants.js';

export const ROUTES = {
  HOME: FRONTEND_ROUTES.HOME,
  AUTH: FRONTEND_ROUTES.AUTH,
  EXPLORE: FRONTEND_ROUTES.EXPLORE,
  CULTURE: FRONTEND_ROUTES.CULTURE,
  ABOUT: FRONTEND_ROUTES.ABOUT,
  SIGNUP: SHARED_API_ROUTES.SIGNUP,
  SIGNIN: SHARED_API_ROUTES.SIGNIN,
};

export const API_ENDPOINTS = {
  CONFIG: SHARED_API_ROUTES.CONFIG,
};

export const ENDPOINTS = { ...ROUTES, ...API_ENDPOINTS };
